// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuQ_1DE3YgEqq8duuZVCLa9kLHxoEj1SU',
    appId: '1:636022737942:web:a54fe243159a0435bb3937',
    messagingSenderId: '636022737942',
    projectId: 'wallroom-4aa8b',
    authDomain: 'wallroom-4aa8b.firebaseapp.com',
    storageBucket: 'wallroom-4aa8b.firebasestorage.app',
    measurementId: 'G-N0S59STQ37',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHBhd0h__o16SfiPuIQQHmaEZqtLu4zc4',
    appId: '1:636022737942:ios:8e1fbaf5a6ba7da9bb3937',
    messagingSenderId: '636022737942',
    projectId: 'wallroom-4aa8b',
    storageBucket: 'wallroom-4aa8b.firebasestorage.app',
    iosBundleId: 'com.example.wallroom',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHBhd0h__o16SfiPuIQQHmaEZqtLu4zc4',
    appId: '1:636022737942:ios:8e1fbaf5a6ba7da9bb3937',
    messagingSenderId: '636022737942',
    projectId: 'wallroom-4aa8b',
    storageBucket: 'wallroom-4aa8b.firebasestorage.app',
    iosBundleId: 'com.example.wallroom',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ9-h-aN7K5nd7Ms3pD270OA1seN8kFak',
    appId: '1:636022737942:android:eb69a98e9b0ae9d6bb3937',
    messagingSenderId: '636022737942',
    projectId: 'wallroom-4aa8b',
    storageBucket: 'wallroom-4aa8b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuQ_1DE3YgEqq8duuZVCLa9kLHxoEj1SU',
    appId: '1:636022737942:web:002d44785b1afde1bb3937',
    messagingSenderId: '636022737942',
    projectId: 'wallroom-4aa8b',
    authDomain: 'wallroom-4aa8b.firebaseapp.com',
    storageBucket: 'wallroom-4aa8b.firebasestorage.app',
    measurementId: 'G-LJD0EYCRMD',
  );

}